---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springci/spring-data-8-jdk-with-mongodb

inputs:
- name: spring-data-mongodb-github

outputs:
- name: spring-data-mongodb-artifactory

caches:
- path: maven

run:
  path: spring-data-mongodb-github/ci/build.sh
